@echo off
echo Starting Dooley's Building Solutions Systems...
cd /d "%~dp0"

echo [1/2] Starting Local Asset Web Server (Port 3001)...
start "Asset Backend Server" cmd /k "npx tsx server.ts"

echo [2/2] Starting Development Frontend (Port 3000)...
start "React Frontend" cmd /k "npm run dev"

echo Waiting for systems to spin up...
timeout /t 3 /nobreak > NUL

echo Opening Interface...
start http://localhost:3000
