require 'sketchup.rb'

module HouseShellBuilder
  # Load core modules
  loader = File.join(File.dirname(__FILE__), 'core', 'helpers.rb')
  require loader if File.exist?(loader)
  
  loader = File.join(File.dirname(__FILE__), 'core', 'geometry.rb')
  require loader if File.exist?(loader)

  def self.show_dialog
    options = {
      :dialog_title => "House Shell Builder",
      :preferences_key => "com.blueprintdrafter.houseshellbuilder",
      :scrollable => true,
      :resizable => true,
      :width => 1200,
      :height => 800,
      :left => 100,
      :top => 100,
      :min_width => 400,
      :min_height => 400,
      :style => UI::HtmlDialog::STYLE_DIALOG
    }
    @dialog = UI::HtmlDialog.new(options)
    
    # Point to the local UI file for the standalone experience
    ui_path = File.join(File.dirname(__FILE__), 'ui', 'index.html')
    @dialog.set_file(ui_path)
    
    @dialog.add_action_callback("execute_ruby") { |action_context, code|
      begin
        # Execute the Ruby code generated by the web app
        eval(code)
      rescue => e
        UI.messagebox("Error executing Ruby: #{e.message}\n\n#{e.backtrace.first}")
      end
    }
    
    @dialog.show
  end

  unless file_loaded?(__FILE__)
    menu = UI.menu('Plugins')
    menu.add_item('House Shell Builder') {
      self.show_dialog
    }
    file_loaded(__FILE__)
  end
end
